# Generated by Django 5.1.1 on 2024-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_author_alter_order_user_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
